### ISSUE TITLE
VulkanCompute possible without Surfaces?

### ISSUE THREAD

**Issue by fzwoch** [vulkan-go/asche#4]
I was looking at this Vulkan-Compute example: https://github.com/Erkaman/vulkan_minimal_compute

As far as I understood this example uses Vulkan-Compute shaders without using any surfaces. I was looking into if it was feasible to mimic this example in `asche`.

I found this check

`platform.go:131`
```go
	// Make sure the surface is here if required
	mode := app.VulkanMode()
	if mode.Has(VulkanPresent) { // so, a surface is required and provided
		p.surface = app.VulkanSurface(p.instance)
		if p.surface == vk.NullSurface {
			return nil, errors.New("vulkan error: surface required but not provided")
		}
	}
```

So it seems that if the `VulkanMode` is set to `VulkanCompute` only it still expects a surface. I'm not sure if I misunderstood the basic concept - but would it be a feasible feature request to make Vulkan-Compute shaders work without having surfaces?

**Comment by xlab** [comment]
> So it seems that if the VulkanMode is set to VulkanCompute only it still expects a surface.

This assumption is different from the check logic, which actually checks if mode has `VulkanPresent` bit. I'm not sure of the real behaviour, but if it requires a surface even without `VulkanPresent` bit, then it's a bug.

I tested my lib on Amazon instance with GPU, so the compute mode works in general, but I didn't invested much time for testing corner cases.

**Comment by fzwoch** [comment]
Here is an example:

```go
package main

import (
	as "github.com/vulkan-go/asche"
	vk "github.com/vulkan-go/vulkan"
)

type application struct {
	as.BaseVulkanApp
}

func (a *application) VulkanMode() as.VulkanMode {
	return as.VulkanCompute
}

func main() {
	if err := vk.SetDefaultGetInstanceProcAddr(); err != nil {
		panic(err)
	}

	if err := vk.Init(); err != nil {
		panic(err)
	}

	app := &application{}

	_, err := as.NewPlatform(app)
	if err != nil {
		panic(err)
	}
}
```

This code will panic:

```shell
2019/07/24 15:54:22 vulkan: enabling 0 instance extensions
2019/07/24 15:54:22 vulkan: enabling 0 device extensions
panic: vulkan error: surface required but not provided

goroutine 1 [running]:
main.main()
```

The check looks like that
```
func (v VulkanMode) Has(mode VulkanMode) bool {
	return v&mode != 0
}
```

Initially I thought `VulkanPresent` would be a representation of `VulkanCompute | VulcanGraphics` because of:

```go
const (
	VulkanNone VulkanMode = iota
	VulkanCompute
	VulkanGraphics
	VulkanPresent
)
```

These will actually result in `0,1,2,3`.  But since I found this:

`application.go:60`
```go
DefaultVulkanMode       = VulkanCompute | VulkanGraphics | VulkanPresent
```

It feels like these were supposed to be real bit fields. So maybe something like this one was the intend?

```go
const (
	VulkanNone VulkanMode = (1 << iota) >> 1
	VulkanCompute
	VulkanGraphics
	VulkanPresent
)
```

**Comment by xlab** [comment]
> It feels like these were supposed to be real bit fields. So maybe something like this one was the intend?

Yes, that is a mix-up. Thanks for investigation.

**Comment by xlab** [comment]
P.S. very cool example of a compute shader. I previously only found some basic buffer manipulation examples.

**Comment by fzwoch** [comment]
Yeah its pretty cool. Also a very nice introduction to Vulkan imo.

Thanks for addressing the Vulkan modes!
